from servidor_rest import app

if __name__ == "__main__":
    print("🎉 BIENVENIDO A UVSHOP")
    print("🎯 SISTEMA DE COMERCIO ELECTRÓNICO - SERVIDOR REST")
    print("="*80)
    print("🚀 Iniciando servidor REST...")
    print("📡 API disponible en: http://localhost:5000/api")
    print("\n🌐 TODOS LOS ENDPOINTS DISPONIBLES:")
    print("\n📋 GET (LEER):")
    print("   • GET    /api - Información de la API")
    print("   • GET    /api/metodos - Lista TODOS los métodos disponibles")
    print("   • GET    /api/usuarios - Lista de usuarios")
    print("   • GET    /api/productos - Lista de productos") 
    print("   • GET    /api/pedidos - Lista de pedidos")
    print("   • GET    /api/casos-uso/factory-pedidos - Factory Pattern")
    print("\n➕ POST (CREAR):")
    print("   • POST   /api/usuarios - Crear nuevo usuario")
    print("   • POST   /api/productos - Crear nuevo producto")
    print("   • POST   /api/pedidos - Crear nuevo pedido")
    print("\n✏️ PUT (ACTUALIZAR COMPLETO):")
    print("   • PUT    /api/productos/<id> - Actualizar producto completo")
    print("   • PUT    /api/pedidos/<id> - Actualizar pedido completo")
    print("\n🗑️ DELETE (ELIMINAR):")
    print("   • DELETE /api/productos/<id> - Eliminar producto")
    print("   • DELETE /api/pedidos/<id> - Eliminar pedido")
    print("\n🔄 PATCH (ACTUALIZAR PARCIAL):")
    print("   • PATCH  /api/pedidos/<id>/estado - Cambiar solo estado")
    print("="*80)
    print("💡 TOTAL: 13 endpoints con 5 métodos HTTP (GET, POST, PUT, DELETE, PATCH)")
    print("🔥 ¡API REST COMPLETA CON CRUD FUNCIONAL!")
    print("="*80)
    
    # Iniciar servidor REST
    app.run(host='0.0.0.0', port=5000, debug=False)